### PR TITLE
User data - added :avatar, :zipcode, :state to user personal data

### PR DESCRIPTION
**Pull request by escoffon**
@7seven7lst This PR has the changes to implement avatars in the Opo::Core::UserPersonal object. This uses ActiveStorage (with some extensions I added).

You will have to `bundle install` to pick up the latest fl-framework gem, then upgrade the vendor assets with `bin/rails g fl:framework:js_assets --nodoc`, and rebuild the database from scratch with `bash db/pg/prepare_db.sh development` (use `bash db/pg/prepare_db.sh development noseed` if you don't want to seed the db with some initial users).

Every new user gets the default avatar, which I copied from Allen's wireframe.

I don't have tests yet for updating the avatar from a (web) client, but we can do it from a Rails script for the demo.

Take a look. When you OK the PR, I'll push it to master. Then we can update demo from master, and see what happens. I'll do that work and see if I can figure out the react code to make the changes.

### CODE REVIEW

**Comment by escoffon** [comment]
@7seven7lst I didn't add a :status attribute for the user, because I wasn't sure what that means. I think that might actually be status for the opportunity (received, processed, etc...), but I'm not sure.

**Comment by 7seven7lst** [comment]
tried run `bin/rails g fl:framework:js_assets --nodoc`
but have this error
~~~
/Users/shengtaoli/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant': uninitialized constant Fl::Framework::Attachment::ActiveStorage (NameError)
~~~

**Comment by 7seven7lst** [comment]
nvmd. think after I did a `bundle update` things works fine

**Comment by 7seven7lst** [comment]
question: how are we supposed to retrieve the image from url: `/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lOTWpBd2VESXdNRDRHT2daRlZEb0tjM1J5YVhCVU9nOWlZV05yWjNKdmRXNWtTU0lZY21kaVlTZ3lOVFVzTWpVMUxESTFOU3d3S1FZN0JsUT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--9d2c75b897d1d139084e3078a7b383b8fbe6fa38/default_avatar.png`? 
I tried hit `localhost:3000/<above_url>` and not getting it.

**Comment by escoffon** [comment]
@7seven7lst I sent you an email about your question, but I'll add it here so that it is in the paperwork:

You should be getting it. Is this the URL from the user avatar? The user-data changes are not in demo, so if you run from a demo branch it won't work.

Also, you may want to run `bin/spring stop` and then start the server. Spring caches the Rails configuration so that the app starts up faster, but is not very good at detecting changes.

Here's how you can get a url from the Rails console. In the example, from the first available user.

First, start the Rails console: `bin/rails c`. Then get user and UserPersonal:

```
u = Opo::Core::User.all.first

p = u.personal
```

To get the URL for the :thumb style of the avatar:

```
url = p.avatar_variant_url(:thumb, host: 'localhost:3333')
```

You should be able to copy the value of `url` and paste it into a browser. Note that for _url you have to provide a host name.

To get the path component:

```
path = p.avatar_variant_path(:xlarge)
```

This one is missing the host component. By the way, if you want to see what the hash representation of the avatar is, you can do this:

```
h = p.to_hash(u, except: [ :images, :policies ])
```

(sorry I just realized a committed a bug from when I was testing attachments. In real life, you won't need the :except parameter.)

For example, here is the avatar representation:

```
h[:avatar]
 => {:type=>"ActiveStorage::Attached::One", :name=>"avatar", :attachments=>[{:type=>"ActiveStorage::Attachment", :name=>"avatar", :content_type=>"image/png", :original_filename=>"default_avatar.png", :original_byte_size=>17615, :variants=>[{:style=>:xlarge, :params=>{:resize=>"200x200>", :strip=>true, :background=>"rgba(255,255,255,0)"}, :url=>"/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lOTWpBd2VESXdNRDRHT2daRlZEb0tjM1J5YVhCVU9nOWlZV05yWjNKdmRXNWtTU0lZY21kaVlTZ3lOVFVzTWpVMUxESTFOU3d3S1FZN0JsUT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--9d2c75b897d1d139084e3078a7b383b8fbe6fa38/default_avatar.png"}, {:style=>:large, :params=>{:resize=>"72x72>", :strip=>true, :background=>"rgba(255,255,255,0)"}, :url=>"/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lMTnpKNE56SStCam9HUlZRNkNuTjBjbWx3VkRvUFltRmphMmR5YjNWdVpFa2lHSEpuWW1Fb01qVTFMREkxTlN3eU5UVXNNQ2tHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6efa46ab1064fedd42c82706872634460c9493e7/default_avatar.png"}, {:style=>:medium, :params=>{:resize=>"48x48>", :strip=>true, :background=>"rgba(255,255,255,0)"}, :url=>"/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lMTkRoNE5EZytCam9HUlZRNkNuTjBjbWx3VkRvUFltRmphMmR5YjNWdVpFa2lHSEpuWW1Fb01qVTFMREkxTlN3eU5UVXNNQ2tHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--ae79cade6e005b0c20f0d493660450f9dc914ee9/default_avatar.png"}, {:style=>:thumb, :params=>{:resize=>"32x32>", :strip=>true, :background=>"rgba(255,255,255,0)"}, :url=>"/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lMTXpKNE16SStCam9HUlZRNkNuTjBjbWx3VkRvUFltRmphMmR5YjNWdVpFa2lHSEpuWW1Fb01qVTFMREkxTlN3eU5UVXNNQ2tHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--0efe365c790b18d1aa7f8227b7118e0dd7f40b17/default_avatar.png"}, {:style=>:list, :params=>{:resize=>"24x24>", :strip=>true, :background=>"rgba(255,255,255,0)"}, :url=>"/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lMTWpSNE1qUStCam9HUlZRNkNuTjBjbWx3VkRvUFltRmphMmR5YjNWdVpFa2lHSEpuWW1Fb01qVTFMREkxTlN3eU5UVXNNQ2tHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--547a28ae28297565c0d34d1dc102f849e10e7bcc/default_avatar.png"}, {:style=>:original, :params=>{:strip=>true, :background=>"rgba(255,255,255,0)"}, :url=>"/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9LYzNSeWFYQlVPZzlpWVdOclozSnZkVzVrU1NJWWNtZGlZU2d5TlRVc01qVTFMREkxTlN3d0tRWTZCa1ZVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--59fa59577c1304c5c7e3bf274b6c8cb6e23b132a/default_avatar.png"}], :created_at=>Thu, 17 Jan 2019 19:42:55 UTC +00:00}]}
```

and formatted for your convenience:

```
{
  :type => "ActiveStorage::Attached::One",
  :name => "avatar",
  :attachments => [
    {
      :type => "ActiveStorage::Attachment",
      :name => "avatar",
      :content_type => "image/png",
      :original_filename => "default_avatar.png",
      :original_byte_size => 17615,
      :variants => [
        {
          :style => :xlarge,
          :params => { :resize => "200x200>", :strip => true, :background => "rgba(255,255,255,0)"
          },
          :url => "/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lOTWpBd2VESXdNRDRHT2daRlZEb0tjM1J5YVhCVU9nOWlZV05yWjNKdmRXNWtTU0lZY21kaVlTZ3lOVFVzTWpVMUxESTFOU3d3S1FZN0JsUT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--9d2c75b897d1d139084e3078a7b383b8fbe6fa38/default_avatar.png"
        }, {
          :style => :large,
          :params => { :resize => "72x72>", :strip => true, :background => "rgba(255,255,255,0)" },
          :url => "/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lMTnpKNE56SStCam9HUlZRNkNuTjBjbWx3VkRvUFltRmphMmR5YjNWdVpFa2lHSEpuWW1Fb01qVTFMREkxTlN3eU5UVXNNQ2tHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6efa46ab1064fedd42c82706872634460c9493e7/default_avatar.png"
        }, {
          :style => :medium,
          :params => { :resize => "48x48>", :strip => true, :background => "rgba(255,255,255,0)" },
          :url => "/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lMTkRoNE5EZytCam9HUlZRNkNuTjBjbWx3VkRvUFltRmphMmR5YjNWdVpFa2lHSEpuWW1Fb01qVTFMREkxTlN3eU5UVXNNQ2tHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--ae79cade6e005b0c20f0d493660450f9dc914ee9/default_avatar.png"
        }, {
          :style => :thumb,
          :params => { :resize => "32x32>", :strip => true, :background => "rgba(255,255,255,0)" },
          :url => "/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lMTXpKNE16SStCam9HUlZRNkNuTjBjbWx3VkRvUFltRmphMmR5YjNWdVpFa2lHSEpuWW1Fb01qVTFMREkxTlN3eU5UVXNNQ2tHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--0efe365c790b18d1aa7f8227b7118e0dd7f40b17/default_avatar.png"
        }, {
          :style => :list,
          :params => { :resize => "24x24>", :strip => true, :background => "rgba(255,255,255,0)" },
          :url => "/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lMTWpSNE1qUStCam9HUlZRNkNuTjBjbWx3VkRvUFltRmphMmR5YjNWdVpFa2lHSEpuWW1Fb01qVTFMREkxTlN3eU5UVXNNQ2tHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--547a28ae28297565c0d34d1dc102f849e10e7bcc/default_avatar.png"
        }, {
          :style => :original,
          :params => { :strip => true, :background => "rgba(255,255,255,0)" },
          :url => "/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--47e90ff8163afa818bdb7df58b7781ce56f47ea1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9LYzNSeWFYQlVPZzlpWVdOclozSnZkVzVrU1NJWWNtZGlZU2d5TlRVc01qVTFMREkxTlN3d0tRWTZCa1ZVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--59fa59577c1304c5c7e3bf274b6c8cb6e23b132a/default_avatar.png"
        }
      ],
      :created_at => 'Thu, 17 Jan 2019 19:42:55 UTC +00:00'
    }
  ]
}
```

From a JS environment, once you have an OpoCoreUser object, the `personal` property is an OpoCoreUserPersonal, and the `avatar` property is a `ActiveSupportAttachedOne`. You can get a (path) URL like this:

```
u.personal.avatar.variant_url('thumb');
```

Look at `mocha/request/opo_core_users.js` for an example.

**Pull request merged**
